// "use client"
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import BinaryBackground from "./components/BinaryBackground/BinaryBackground";
import Navbar from "./components/Navbar/Navbar";
import Navbar1 from "./components/Navbar1/Navbar1";
import VerticalNavbar from "./components/VerticalNavbar/VerticalNavbar";
import VerticalNavbar1 from "./components/VerticalNavbar1/VerticalNavbar1";
import VerticalNavbar3 from "./components/VerticalNavbar3/VerticalNavbar3";
import VerticalNavbar4 from "./components/VerticalNavbar4/VerticalNavbar4";
import BinaryBack from "./components/BinarayBack/BinaryBack";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-arp="" data-theme="dark" className="scroll-smooth">
      <body
        className={`${inter.variable} ${poppins.variable} antialiased`}
      >
        {/* <BinaryBackground /> */}
        <BinaryBack />
        {/* <Navbar1 /> */}
        {/* <VerticalNavbar /> */}
        {/* <VerticalNavbar1 /> */}
        {/* <VerticalNavbar3 /> */}
        <VerticalNavbar4 />
        {children}
      </body>
    </html>
  );
}