// app/layout.jsx
"use client"
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import BinaryBackground from "./components/BinaryBackground/BinaryBackground";
import Navbar1 from "./components/Navbar1/Navbar1";
import Footer from "./components/Footer/Footer";
import VerticalNavbar4 from "./components/VerticalNavbar4/VerticalNavbar4";
import ClientLayout from "@/components/ui/ClientLayout/ClientLayout";
import BinaryBack from "./components/BinarayBack/BinaryBack";
import { AuthProviders } from "@/providers/AuthProviders";
import AuthDebug from "./components/AuthDebug";
import Chatbot from "./components/Chatbot/Chatbot";
import AnimatedCursor from "react-animated-cursor";
// import AuthDebug from "./components/AuthDebug";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-arp="" data-theme="dark" className="scroll-smooth">
      <body
        className={`${inter.variable} ${poppins.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        {/* The background is a fixed layer behind everything */}
        {/* <BinaryBackground /> */}
        <BinaryBack />

        {/* This container holds the actual page layout */}
        <div className="relative z-10 flex flex-col min-h-screen">
          {/* {!hideLayout && <Navbar1 />}
          <VerticalNavbar4 /> */}

          <main className="flex-grow">

            {/* <AnimatedCursor
              showSystemCursor={true}
              color="#fff"
              innerSize={8}
              outerSize={35}
              innerScale={1}
              outerScale={1.7}
              outerAlpha={0}
              outerStyle={{
                border: "2px solid rgba(0,150,255,0.8)",
                backgroundColor: "transparent",
                borderRadius: "50%",
              }}
              innerStyle={{
                backgroundColor: "rgba(0,150,255,1)",
                borderRadius: "50%",
              }}
            /> */}

            <ClientLayout>
              <AuthProviders>
                {children}
                <Chatbot />
              </AuthProviders>
            </ClientLayout>
          </main>

          {/* Footer is always at the bottom of the flex container */}
          {/* {!hideLayout && <Footer />} */}
        </div>

        {/* Debug component */}
        {/* <AuthDebug /> */}
      </body>
    </html>
  );
}